### PR TITLE
Added text flair

### PR DESCRIPTION
**Pull request by existentialcomics**
Added subreddit text flair, I put it below the username and points, make sure to check it out on /r/nfl, which has very short text flair, /r/funny which has medium length, and /r/askscience which has very long text flair if you want to change the layout.

### CODE REVIEW

**Comment by talklittle** [comment]
Nice, I'll try it out soon! Thank you!

**Comment by talklittle** [comment]
Hi there, sorry but this pull request will be put on hold indefinitely. I'm rewriting the app from scratch to rid myself of GPL's restrictions. I'm not finding GPL to be the kind of license I'd want to subject myself to. Thank you for understanding and for your contribution.

**Comment by whyman** [comment]
Hello freeordie, 

There is now a community for of RiF, if you are interested, please feel free to resubmit this over at https://github.com/zagaberoo/diode.

Software Freedom is important.

**Comment by existentialcomics** [comment]
Excellent! I was hoping someone would do this. I will make sure to do so, I think the text flair is fairly important for some of the subs.

**Pull request closed without merging**
